### ISSUE TITLE
Feature request: Named broadcasts

### ISSUE THREAD

**Issue by adrn** [dfm/spotify-party#3]
It'd be cool to be able to make rooms like: https://distance.dfm.io/pricewhelan/german-techno-party

**Comment by dfm** [comment]
Yes - I like that idea. And I like the idea of linking it to the username!

**Comment by dfm** [comment]
This is not yet implemented, but I did make some progress. Now rooms are named random genres. For example:

```
pop-ballad
folk-motown
hard-merengue
mainstream-opera
psychedelic-country
```

**Comment by dfm** [comment]
This now works! Try clicking on the "channel" name before you start the broadcast.
